language: C

install:
# Set up miniconda
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=3.5 pip
- source activate test-environment

# Now install our dependencies
# TODO: just install `documentation/rtd-conda-environment.yml` instead of duplicating here?
- conda config --add channels conda-forge
- conda config --add channels astropy
- conda install click pytest sphinx pyyaml ruamel.yaml cython numpy scipy matplotlib bokeh uncertainties pandas astropy
- python -m pip install pytest-cov jsonschema sphinx-rtd-theme
- python -m pip install git+https://github.com/gammapy/gammapy.git#egg=gammapy

script:
- export PYTHONPATH=.:$PYTHONPATH
- python -m pytest -v --cov=gammacat
- python make.py --help
#- ./make.py check
#- ./make.py output
#- ./make.py webpage
- python make.py all
- cd documentation && make html
