language: C

install:
# Set up miniconda
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a

# Now install our dependencies
- conda env create -f environment.yml
- source activate gamma-cat

script:
- export PYTHONPATH=.:$PYTHONPATH
- python -m pytest -v --cov=gammacat
- python make.py --help
#- ./make.py check
#- ./make.py output
#- ./make.py webpage
- python make.py all
- cd documentation && make html
