name: gamma-cat

channels:
  - conda-forge
  - astropy

dependencies:
  - python=3
  - sphinx
  - matplotlib
  - bokeh
  - pyyaml
  - ruamel.yaml
  - jsonschema
  - astropy

  - pip:
    - git+https://github.com/gammapy/gammapy.git#egg=gammapy
