# Conda environment for gamma-cat development
#
# Install:    conda env create -f environment.yml
# Update:     conda env update -f environment.yml
# Activate:   conda activate gamma-cat
# Deactivate: conda deactivate

name: gamma-cat

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pytest
  - pytest-cov
  - cython
  - scipy
  - pandas
  - uncertainties
  - click
  - sphinx
  - sphinx_rtd_theme
  - matplotlib
  - bokeh
  - pyyaml
  - ruamel.yaml
  - jsonschema
  - astropy
  - regions

  - pip:
    - sphinxcontrib.datatemplates
    - git+https://github.com/gammapy/gammapy.git#egg=gammapy
